print ("=======================================")
print ("            PROGRAM PYTHON             ")
print ("         OLEH: IBNU HAMBAL RCH         ")
print ("            KELAS: X PPLG 2            ")
print ("=======================================")